# Generated by Django 5.1 on 2024-09-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_productuserrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductUserRating',
        ),
    ]
